export STARSHIP_CONFIG="$HERE/../termux/starship.toml"

alias updategpg='echo UPDATESTARTUPTTY | gpg-connect-agent'

if ! gpg-agent -s; then
  gpgconf --launch gpg-agent
  updategpg
fi

export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
