export STARSHIP_CONFIG="$HERE/../termux/starship.toml"

alias updategpg='export GPG_TTY=$(tty); echo UPDATESTARTUPTTY | gpg-connect-agent'

gpg-connect-agent /bye
updategpg

export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

unset KRR_PROXY
