#!/bin/bash
echo "post-stop: $SERVICE_RESULT $EXIT_CODE $EXIT_STATUS"

[ "$SERVICE_RESULT" = success ] && exit

[ "$4" = user ] || [ "$4" = user-runtime-dir ] && exit
user="$1"
host="$2"
unit="$3"
full="$5"

kpush=/opt/dotfiles/kpush
systemctl=systemctl
if [ "$user" != root ]; then
  systemctl+=' --user'
  host="$user@$host"
fi

host+=": $unit: $SERVICE_RESULT $EXIT_CODE $EXIT_STATUS"
$systemctl status "$full" | $kpush -t "<b>$host</b>  #fail"
