#!/bin/bash

HERE="$(dirname "$(realpath "$0")")"

if [ -e ~/.zshrc ]; then
  size=$(stat -c%s ~/.zshrc)
  if [ $size -eq 0 ]; then
    rm ~/.zshrc
  else
    echo ~/.zshrc "already exists, skipping."
    exit 1
  fi
fi

ln -s "$HERE/.zshrc" ~/.zshrc
